<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RDPC42" failures="8" tests="29" name="Test" time="14.835" errors="0" timestamp="2023-06-09T18:10:36 IST">
  <testcase classname="api.test.LoginTests" name="testLogin" time="4.918"/>
  <testcase classname="api.test.LoginTests" name="testResendOtp" time="0.638"/>
  <testcase classname="api.test.LoginTests" name="testVerifyOtp" time="0.41"/>
  <testcase classname="api.test.PincodeServiceableTests" name="pincodeServiceable" time="0.404"/>
  <testcase classname="api.test.DetectDeviceTests" name="testDetectDevice" time="0.884"/>
  <testcase classname="api.test.ListVariantsTests" name="testListVariantQuestions" time="0.58"/>
  <testcase classname="api.test.GetCommonQuoteTests" name="testGetCommonQuotes" time="0.487"/>
  <testcase classname="api.test.GetAddressTests" name="testGetAddress" time="0.443"/>
  <testcase classname="api.test.AddUpdateAddressTests" name="testAddUpdateAddress" time="0.366"/>
  <testcase classname="api.test.ApplicablePaymentMethodsTests" name="testApplicablePaymentMethods" time="0.407"/>
  <testcase classname="api.test.VerifyIfscTests" name="testVerifyIfsc" time="0.322"/>
  <testcase classname="api.test.OrderAvailableTimeslotsTests" name="testOrderAvaialbleTimeslots" time="0.348"/>
  <testcase classname="api.test.ApplyCouponTests" name="testApplyCoupon" time="0.299"/>
  <testcase classname="api.test.ApplyCouponTests" name="testRevokeCoupon" time="0.303"/>
  <testcase classname="api.test.PlaceOrderTests" name="testPlaceOrder" time="0.295">
    <failure type="java.lang.AssertionError" message="expected [200] but found [422]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [422]
at api.test.PlaceOrderTests.testPlaceOrder(PlaceOrderTests.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testPlaceOrder -->
  <testcase classname="api.test.ListOrdersTests" name="testListOrders" time="0.291"/>
  <testcase classname="api.test.NotificationCountTests" name="testNotificationCount" time="0.294"/>
  <testcase classname="api.test.OrderDetailsTests" name="testOrderDetails" time="0.006">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.OrderDetailsEndPoints.orderDeatails(OrderDetailsEndPoints.java:10)
at api.test.OrderDetailsTests.testOrderDetails(OrderDetailsTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testOrderDetails -->
  <testcase classname="api.test.SupportQuestionsTests" name="testSupportQuestions" time="0.507"/>
  <testcase classname="api.test.RequestCallbackTests" name="testCreateTicket" time="0.345"/>
  <testcase classname="api.test.RequestCallbackTests" name="testAlreadyCreated" time="0.289"/>
  <testcase classname="api.test.ChangePaymentMethodTests" name="testChangePaymentMethod" time="0.004">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.ChangePaymentMethodEndPoints.changePaymentMethod(ChangePaymentMethodEndPoints.java:10)
at api.test.ChangePaymentMethodTests.testChangePaymentMethod(ChangePaymentMethodTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testChangePaymentMethod -->
  <testcase classname="api.test.RescheduleOrderTests" name="testRescheduleOrder" time="0.292">
    <failure type="java.lang.AssertionError" message="expected [Order has been rescheduled] but found [Invalid or missing parameters]">
      <![CDATA[java.lang.AssertionError: expected [Order has been rescheduled] but found [Invalid or missing parameters]
at api.test.RescheduleOrderTests.testRescheduleOrder(RescheduleOrderTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testRescheduleOrder -->
  <testcase classname="api.test.ViewProfileTests" name="testViewProfile" time="0.291"/>
  <testcase classname="api.test.UpdateProfileTests" name="testUpdateProfile" time="0.571">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;Profile has been updated&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "Profile has been updated"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Short.parseShort(Short.java:137)
at java.base/java.lang.Short.parseShort(Short.java:163)
at java_lang_Short$parseShort.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.common.path.ObjectConverter.convertObjectTo(ObjectConverter.groovy:37)
at io.restassured.path.json.JsonPath.getShort(JsonPath.java:287)
at api.test.UpdateProfileTests.testUpdateProfile(UpdateProfileTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateProfile -->
  <testcase classname="api.test.CancelOrderTests" name="testCancelOrder" time="0.008">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.CancelOrderEndPoints.cancelOrder(CancelOrderEndPoints.java:10)
at api.test.CancelOrderTests.testCancelOrder(CancelOrderTests.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCancelOrder -->
  <testcase classname="api.test.CancelOrderTests" name="testCancelSameOrder" time="0.005">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.CancelOrderEndPoints.cancelOrder(CancelOrderEndPoints.java:10)
at api.test.CancelOrderTests.testCancelSameOrder(CancelOrderTests.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCancelSameOrder -->
  <testcase classname="api.test.SaveInstructionsTests" name="testSaveInstructions" time="0.279">
    <failure type="java.lang.AssertionError" message="expected [Instructions have been saved] but found [Order does not exist]">
      <![CDATA[java.lang.AssertionError: expected [Instructions have been saved] but found [Order does not exist]
at api.test.SaveInstructionsTests.testSaveInstructions(SaveInstructionsTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testSaveInstructions -->
  <testcase classname="api.test.NotificationListTests" name="testNotificationList" time="0.299"/>
</testsuite> <!-- Test -->
